# Generated by Django 3.1.3 on 2021-02-27 09:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JpStopsLahore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=32643)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('stop_n', models.CharField(blank=True, max_length=50, null=True)),
                ('point_x', models.FloatField(blank=True, null=True)),
                ('point_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jp_stops_lahore',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
