# Generated by Django 3.1.3 on 2020-11-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
