# Generated by Django 3.1.3 on 2020-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('eMail', models.EmailField(max_length=40, unique=True)),
                ('passWord', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
